name: visaid_cv_gui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter_tts: ^3.2.2
  camera: 0.10.5+9
  flutter:
    sdk: flutter
  tflite: ^1.1.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
